install:
  postgresql: true
  vault: false

participant:
  id: "BPNL00000007RF54"

iatp:
  # Decentralized IDentifier
  id: "did:web:portal-backend.int.demo.catena-x.net:api:administration:staticdata:did:BPNL00000007RF54"
  trustedIssuers:
    - "did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp"
  sts:
    dim:
      url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal"
    oauth:
      token_url: "https://bpnl00000007rf54-bpdm--golden--record.authentication.eu10.hana.ondemand.com/oauth/token"
      client:
        id: "sb-0d52b7f2-e7d0-4577-9647-f5132921e452!b459174|ica-production-dim-prod-eu10-004-prod-dis-cloud-approuter!b174292"
        secret_alias: "int/edc/bpdm/client-secret"

controlplane:
  env:
    EDC_IAM_TRUSTED-ISSUER_ISSUER1_ID: 'did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp'
  endpoints:
    # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
    management:
      # -- authentication key, must be attached to each 'X-Api-Key' request header
      authKey: <path:bpdm/data/int/edc/bpdm/controlplane-auth#content>
  bdrs:
    server:
      url: "https://bpn-did-resolution-service.int.demo.catena-x.net/api/directory"
  ## Ingress declaration to expose the network service.
  ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "bpdm-edc.int.demo.catena-x.net"
      className: "nginx"
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - management
        - control
        - protocol
      # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
      tls:
        # -- Enables TLS on the ingress resource
        enabled: true
        # -- If present overwrites the default secret name
        secretName: tls-secret

dataplane:
  env:
    EDC_IAM_TRUSTED-ISSUER_ISSUER1_ID: 'did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp'
  endpoints:
    proxy:
      authKey: <path:bpdm/data/int/edc/bpdm/controlplane-auth#content>
  ## Ingress declaration to expose the network service.
  ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "bpdm-edc.int.demo.catena-x.net"
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - public
      # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
      className: "nginx"
      # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
      tls:
        # -- Enables TLS on the ingress resource
        enabled: true
        # -- If present overwrites the default secret name
        secretName: tls-secret
  token:
    signer:
      privatekey_alias: "int/edc/bpdm/dataplane-private-key"
    verifier:
      publickey_alias: "int/edc/bpdm/dataplane-public-key"

postgresql:
  jdbcUrl: "jdbc:postgresql://edc-bpdm-postgres:5432/edc"
  fullnameOverride: "edc-bpdm-postgres"
  primary:
    persistence:
      enabled: true
  auth:
    database: "edc"
    username: "user"
    password: <path:bpdm/data/int/edc/bpdm/postgres-password#content>

vault:
  hashicorp:
    url: "https://vault.demo.catena-x.net"
    token: <path:bpdm/data/int/edc/bpdm/vault-token#content>
    paths:
      secret: /v1/bpdm
  secretNames:
    transferProxyTokenSignerPrivateKey: int/edc/bpdm/dataplane-private-key
    transferProxyTokenSignerPublicKey: int/edc/bpdm/dataplane-public-key
    transferProxyTokenEncryptionAesKey: int/edc/bpdm/aes-key